### ISSUE TITLE
Swagger UI Fails to Load on Startup

### ISSUE THREAD

**Issue by cms79** [Hona/VerticalSliceArchitecture#4]
With a fresh project template, after a clean build and launch of the API, the Swagger UI fails to launch properly due to an extra forward slash in the URL (see screenshot):

![image](https://github.com/Hona/VerticalSliceArchitecture/assets/2441600/7c0c68f3-2bc4-4ee3-8a37-f6682686271a)

It appears that the "launchUrl" property in the launchSettings should be edited to have the forward slash removed.

![image](https://github.com/Hona/VerticalSliceArchitecture/assets/2441600/fa090345-a9c6-49ed-8533-f83abec997fa)

**Comment by Hona** [comment]
Thanks for the report :)

It took me a second to commit & merge what I demoed at DDD Brisbane (including this fix)

Fixed via #5
